/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs:[
    {
      type: 'category',
      label: 'docs',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        { 
          type: 'category',
          label: 'kubernetes',
          items:[
            {type: 'autogenerated', dirName: 'kubernetes'},
          ]          
        },
        { 
          type: 'category',
          label: 'linux',
          items:[
            {type: 'autogenerated', dirName: 'linux'},
          ]          
        },
        { 
          type: 'category',
          label: 'dev&ops',
          items:[
            {type: 'autogenerated', dirName: 'dev&ops'}
          ]          
        },
        // { 
        //   type: 'category',
        //   label: 'algorithms',
        //   items:[
        //     { type: 'autogenerated', dirName: 'algorithms' }
        //   ]          
        // }, 
        { 
          type: 'category',
          label: 'others',
          items:[
            { type: 'autogenerated', dirName: 'others' }
          ]          
        }, 
      ],
    },
  ],
  kubernetes: [{type: 'autogenerated', dirName: 'kubernetes'}],
  linux: [{type: 'autogenerated', dirName: 'linux'}],
  'dev&ops': [{type: 'autogenerated', dirName: 'dev&ops'}],
  others: [{type: 'autogenerated', dirName: 'others'}],

};

module.exports = sidebars;
