/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  k8s: [
    {
      type: 'autogenerated',
      dirName: 'k8s',
    },
  ],
  linux: [
    {
      type: 'autogenerated',
      dirName: 'linux',
    },
  ],
  others: [
    {
      type: 'autogenerated',
      dirName: 'others',
    },
  ],
  'dev&ops':[
    {
      type: 'autogenerated',
      dirName: 'dev&ops',
    },
  ],
  wikipedia: [
    {
      type: 'autogenerated',
      dirName: 'wikipedia',
    },
  ],  
};

export default sidebars;
