kind: Pod
apiVersion: v1
metadata:
  name: my-app
  namespace: dragon
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "sleep", "10000000" ]
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: local
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "localhostpath"
            resources:
              requests:
                storage: 1Gi

