name:  GitHub Pages
on:
  push:
    branches: 
    - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0    

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: setup website
        run: git clone https://github.com/vinloong/docusaurus-website.git website
      
      - name: note setup
        run: mv algorithms/ kubernetes/ 'dev&ops'/ others/ -t website/docs/
      
      - name: build
        run: cd website && npm install && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        
        with:
          deploy_key: ${{ secrets.NOTES_DEPLOY_KEY }}   
         # deploy_key: ${{ secrets.NOTES_DEPLOY_KEY }}            
          publish_dir: ./website/build
